### PR TITLE
Using notifications through node-notifier

### PR DESCRIPTION
**Pull request by prewk**
This was useful to me, might be useful to someone else as well.

It doesn't create any dependencies on `node-notifier` or anything, it's very optional.

### CODE REVIEW

**Comment by diegodurli** [comment]
Hey @prewk!

Thank you for this PR, loved the idea!

However, don't you think would be useful to have a success message too? Mainly to sinalize a recovery from errors

I guess would be nice to know it's all fine after a few errors being recovered. What you think?

**Comment by prewk** [comment]
Yeah! I think perhaps an onError and onSuccess callback instead of a "notifier" might be the most flexible. That way you can notify however you like in your webpack config instead of depending node-notifier specifically. Fallback = the console.log that's in the code today.

**Comment by diegodurli** [comment]
It's more flexible, indeed @prewk. Do you want to go ahead and submit a PR following this?

**Comment by prewk** [comment]
Sure thing.
tis 16 aug. 2016 kl. 20:21 skrev Diego Durli notifications@github.com:

**Comment by prewk** [comment]
I added some tests as well for added coziness.

Are you going to merge pull request #12? In that case do that first, and I'll change this according to it. It might be cumbersome for the other author otherwise.

**Comment by diegodurli** [comment]
Hi @prewk!

I just merge that PR, so I guess would be nice for you to update yours.
Sorry about that @prewk!

Thank you for such a great feature! 👍

**Comment by diegodurli** [comment]
@prewk, I'm just updating the package patch version now and publishing to NPM. Going to update `master` to reflect it now. Just to let you know.

**Comment by prewk** [comment]
@diegodurli np I'm syncing atm. I was wondering though, what's the purpose of this?

```
function isFunction(x) {
  return Object.prototype.toString.call(x) == '[object Function]';
}
```

instead of just `typeof x === 'function'`?

**Comment by diegodurli** [comment]
Agreed @prewk, nowadays its not necessary anymore to have this test, `typeof` is enough for this purpose. We can start testing it directly.

**Comment by diegodurli** [comment]
@prewk this one can be closed then? I just merged your newest PR.

**Comment by prewk** [comment]
Yup

**Pull request closed without merging**
